#!/usr/bin/env python3
"""
Lyrics Booklet Generator — Python + Typst pipeline.
Generates a printer-ready A4 PDF with dual-column bilingual lyrics.

Usage:
  python3 generate_booklet.py <data_module.py> [--font-dir /path/to/fonts] [--output out.pdf]

The data module must export a `TRACKS` list:
  TRACKS = [
    ("01", "Song Title", "feat. Artist", [
      ("Section Label", [
        ("English line", "中文翻译"),
        ...
      ], is_chorus=False),  # is_chorus optional (default False)
      ...
    ]),
    ...
  ]
"""

import sys, os, argparse

def esc(s):
    """Escape special Typst characters."""
    return s.replace("\\", "\\\\").replace("#", "\\#")

def build_typst(tracks, font_dir, en_font="Inter", zh_font="Noto Sans CJK SC",
                en_size="12pt", zh_size="11pt", title_size="20pt",
                en_style='"italic"', margin_left="16mm", margin_right="12mm",
                margin_top="14mm", margin_bottom="14mm",
                album_title="LYRICS", album_subtitle="中英对照歌词集",
                artist="Unknown", label_year="", cover_color="white",
                cover_text_color="black"):
    """Generate Typst source for a bilingual lyrics booklet."""

    lines = []
    doc = lines.append

    # Document setup
    doc(f'// Bilingual Lyrics Booklet — Generated by lyrics-booklet skill')
    doc(f'#set document(title: "{esc(album_title)}", author: "{esc(artist)}")')
    doc(f'#set page(paper: "a4", margin: (left: {margin_left}, right: {margin_right}, top: {margin_top}, bottom: {margin_bottom}),')
    doc(f'  numbering: "1", number-align: center)')
    doc('')
    doc('#set page(footer: context [')
    doc(f'  #set text(size: 7pt, font: "{zh_font}", fill: luma(160))')
    doc('  #counter(page).display()')
    doc('])')
    doc(f'#set text(size: {en_size}, font: "{zh_font}", lang: "zh")')
    doc('')

    # ---- COVER ----
    doc(f'#set page(fill: {cover_color})')
    doc(f'#set text(fill: {cover_text_color})')
    doc(f'#align(center + horizon)[#v(60mm)')
    doc(f'#set text(size: 8pt, font: "{zh_font}")')
    doc('#circle(width: 28mm, fill: black)')
    doc('#v(12mm)')
    doc(f'#set text(size: 28pt, weight: "bold", font: "{en_font}")')
    for line in album_title.split('\n'):
        doc(line.strip())
    doc('#v(6mm)')
    doc(f'#set text(size: 14pt, weight: "regular", font: "{zh_font}")')
    doc(album_subtitle)
    doc('#v(8mm)')
    doc(f'#set text(size: 12pt, font: "{en_font}")')
    doc(artist)
    if label_year:
        doc('#v(4mm)')
        doc(f'#set text(size: 9pt, font: "{zh_font}")')
        doc(label_year)
    doc('#v(4mm)')
    doc(f'#set text(size: 8pt, font: "{zh_font}")')
    doc('中英对照歌词集 · 黑白印刷版')
    doc(']')
    doc('')

    # ---- SONGS ----
    total_pairs = 0
    for track_data in tracks:
        track_num, title, featuring, sections = track_data[0], track_data[1], track_data[2], track_data[3]

        doc(f'// {title}')
        doc('#pagebreak()')

        # Title
        doc('#set align(center)')
        doc(f'#text(size: {title_size}, weight: "bold", font: "{en_font}")[{title.upper()}]')
        feat_line = f'Track {track_num}'
        if featuring:
            feat_line += f' · {esc(featuring)}'
        doc(f'#text(size: 8pt, font: "{zh_font}", fill: luma(120))[{feat_line}]')
        doc('#v(10mm)')
        doc('#set align(left)')

        # Sections
        for sec in sections:
            if len(sec) == 2:
                label, pairs = sec
                is_chorus = False
            else:
                label, pairs, is_chorus = sec

            # Section label
            if label and label.strip():
                doc(f'#text(size: 7pt, font: "{zh_font}", fill: luma(140))[{esc(label)}]')
                doc('#v(2mm)')

            # Build table cells
            cells = []
            for en, zh in pairs:
                if en and zh:
                    if is_chorus:
                        cells.append(f"[*#text(size: {en_size}, font: "{en_font}", style: {en_style})[{esc(en)}]*]")
                        cells.append(f"[#text(size: {zh_size}, font: \"{zh_font}\", weight: \"bold\")[{esc(zh)}]]")
                    else:
                        cells.append(f"[#text(size: {en_size}, font: "{en_font}", style: {en_style})[{esc(en)}]]")
                        cells.append(f"[#text(size: {zh_size}, font: \"{zh_font}\", fill: luma(60))[{esc(zh)}]]")
                elif en:
                    if is_chorus:
                        cells.append(f"[*#text(size: {en_size}, font: "{en_font}", style: {en_style})[{esc(en)}]*]")
                    else:
                        cells.append(f"[#text(size: {en_size}, font: "{en_font}", style: {en_style})[{esc(en)}]]")
                    cells.append("[]")
                else:
                    cells.append("[]")
                    cells.append("[]")
                total_pairs += 1

            if cells:
                doc('#table(')
                doc('  columns: (1fr, 1.08fr),')
                doc('  stroke: none,')
                doc('  inset: (x: 0mm, y: 0.3mm),')
                doc('  gutter: 1.8mm,')
                for cell in cells:
                    doc(f'  {cell},')
                doc(')')
                doc('#v(4mm)')
            else:
                doc('#v(4mm)')

    doc('')

    # ---- BACK COVER ----
    doc('#pagebreak()')
    doc(f'#set page(margin: (x: 16mm, y: 20mm))')
    doc(f'#align(center + horizon)[#v(40mm)')
    doc(f'#set text(size: 10pt, style: "italic", font: "{zh_font}", fill: luma(110))')
    doc(f'"{esc(artist)} — {esc(album_title)}"')
    doc('#v(40mm)')
    doc(f'#set text(size: 7pt, font: "{zh_font}", fill: luma(150))')
    doc('Typeset with Typst · Bilingual Lyrics Booklet')
    doc('')
    doc('Printed on A4 · Black & White Laser')
    doc('Personal Use Only · 个人收藏')
    doc(']')

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='Generate bilingual lyrics booklet PDF')
    parser.add_argument('data_module', help='Python module path exporting TRACKS list')
    parser.add_argument('--font-dir', default='/usr/share/fonts', help='Font directory path')
    parser.add_argument('--font-name', default='Noto Serif CJK SC', help='Font family name')
    parser.add_argument('--output', '-o', default='lyrics_booklet.pdf', help='Output PDF path')
    parser.add_argument('--en-size', default='10pt', help='English lyric font size')
    parser.add_argument('--zh-size', default='9.5pt', help='Chinese lyric font size')
    parser.add_argument('--title-size', default='16pt', help='Song title font size')
    parser.add_argument('--margin-left', default='16mm', help='Left margin (binding)')
    parser.add_argument('--margin-right', default='12mm', help='Right margin')
    parser.add_argument('--album-title', default='LYRICS', help='Album title on cover')
    parser.add_argument('--album-subtitle', default='中英对照歌词集', help='Subtitle on cover')
    parser.add_argument('--artist', default='Unknown', help='Artist name')
    parser.add_argument('--label', default='', help='Label & year on cover')
    args = parser.parse_args()

    # Import data module
    sys.path.insert(0, os.path.dirname(os.path.abspath(args.data_module)))
    module_name = os.path.splitext(os.path.basename(args.data_module))[0]
    data = __import__(module_name)
    tracks = data.TRACKS

    print(f'Loaded {len(tracks)} tracks from {args.data_module}')

    # Generate Typst
    typ_content = build_typst(
        tracks, args.font_dir, args.font_name,
        en_size=args.en_size, zh_size=args.zh_size, title_size=args.title_size,
        margin_left=args.margin_left, margin_right=args.margin_right,
        album_title=args.album_title, album_subtitle=args.album_subtitle,
        artist=args.artist, label_year=args.label,
    )

    import tempfile
    with tempfile.NamedTemporaryFile(mode='w', suffix='.typ', delete=False, encoding='utf-8') as f:
        f.write(typ_content)
        typ_path = f.name

    print(f'Generated Typst source ({len(typ_content)} chars)')

    # Compile with Typst
    import typst
    print(f'Compiling with typst {typst.__version__}...')
    pdf_bytes = typst.compile(typ_path, font_paths=[args.font_dir])

    os.unlink(typ_path)

    with open(args.output, 'wb') as f:
        f.write(pdf_bytes)

    size_kb = len(pdf_bytes) / 1024
    print(f'PDF: {args.output} ({size_kb:.0f} KB)')
    print('Done!')


if __name__ == '__main__':
    main()
